//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPDV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTPDV()
        {
            this.CTPGCs = new HashSet<CTPGC>();
        }
    
        public int Id { get; set; }
        public int SoPhieuDV { get; set; }
        public Nullable<int> MaLoaiSP { get; set; }
        public Nullable<int> MaDV { get; set; }
        public int SoLuong { get; set; }
        public decimal TienCong { get; set; }
        public decimal ThanhTien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual PHIEUDICHVU PHIEUDICHVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPGC> CTPGCs { get; set; }
    }
}
