//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPGC
    {
        public int SoPhieuGC { get; set; }
        public int Id { get; set; }
        public int SoLuong { get; set; }
        public double TrongLuong { get; set; }
        public decimal TienCong { get; set; }
        public decimal ThanhTien { get; set; }
    
        public virtual CTPDV CTPDV { get; set; }
        public virtual PHIEUGIACONG PHIEUGIACONG { get; set; }
    }
}
