//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPNH
    {
        public int SoPhieuNhap { get; set; }
        public int MaSP { get; set; }
        public int SoLuong { get; set; }
        public decimal GiaMua { get; set; }
        public decimal ThanhTien { get; set; }
    
        public virtual PHIEUNHAPHANG PHIEUNHAPHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
