//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUGIACONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUGIACONG()
        {
            this.CTPGCs = new HashSet<CTPGC>();
        }
    
        public int SoPhieuGC { get; set; }
        public System.DateTime NgayNhanHang { get; set; }
        public System.DateTime NgayThanhToan { get; set; }
        public int MaTho { get; set; }
        public decimal TongTien { get; set; }
        public int MaNV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPGC> CTPGCs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual THO THO { get; set; }
    }
}
