//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHUTIENNO
    {
        public int SoPhieuNo { get; set; }
        public int SoPhieuBH { get; set; }
        public int MaNV { get; set; }
        public System.DateTime NgayLap { get; set; }
        public System.DateTime NgayTra { get; set; }
        public decimal SoTienNo { get; set; }
        public decimal SoTienTra { get; set; }
        public decimal SoTienConLai { get; set; }
    
        public virtual PHIEUBANHANG PHIEUBANHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
