//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUCHI
    {
        public int SoPC { get; set; }
        public System.DateTime NgayLap { get; set; }
        public string NoiDungChi { get; set; }
        public decimal SoTien { get; set; }
        public int MaNV { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
