//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiBanVang.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuanLiBanVang.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa dịch vụ gia công.
        /// </summary>
        internal static string Cant_edit_DVGC {
            get {
                return ResourceManager.GetString("Cant_edit_DVGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đây là dịch vụ mặc định, không xoá được!.
        /// </summary>
        internal static string DanhSachDichVu_DelError {
            get {
                return ResourceManager.GetString("DanhSachDichVu_DelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xoá khách hàng đã có thực hiện giao dịch với cửa hàng!.
        /// </summary>
        internal static string DanhSachKH_DelError {
            get {
                return ResourceManager.GetString("DanhSachKH_DelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xoá phiếu dịch vụ đã có chi tiết được gia công!.
        /// </summary>
        internal static string DanhSachPDV_DelError {
            get {
                return ResourceManager.GetString("DanhSachPDV_DelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xoá thợ đã thực hiện gia công sản phẩm!.
        /// </summary>
        internal static string DanhSachTho_DelError {
            get {
                return ResourceManager.GetString("DanhSachTho_DelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắn chắc muốn xoá?.
        /// </summary>
        internal static string DetailMessageBox_XacNhanXoa {
            get {
                return ResourceManager.GetString("DetailMessageBox_XacNhanXoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string DiaChi {
            get {
                return ResourceManager.GetString("DiaChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        internal static string GhiChu {
            get {
                return ResourceManager.GetString("GhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức gia công.
        /// </summary>
        internal static string HTGC {
            get {
                return ResourceManager.GetString("HTGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách vãng lai.
        /// </summary>
        internal static string KhachVangLai {
            get {
                return ResourceManager.GetString("KhachVangLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        internal static string LoaiSPKhac {
            get {
                return ResourceManager.GetString("LoaiSPKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đăng ký.
        /// </summary>
        internal static string NgayDK {
            get {
                return ResourceManager.GetString("NgayDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giao.
        /// </summary>
        internal static string NgayGiao {
            get {
                return ResourceManager.GetString("NgayGiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày lập phải là ngày hiện tại!.
        /// </summary>
        internal static string NgayLapPhieu {
            get {
                return ResourceManager.GetString("NgayLapPhieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nhận hàng.
        /// </summary>
        internal static string NgayNhanHang {
            get {
                return ResourceManager.GetString("NgayNhanHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày thanh toán.
        /// </summary>
        internal static string NgayThanhToan {
            get {
                return ResourceManager.GetString("NgayThanhToan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nhận hàng phải là ngày hiện tại!.
        /// </summary>
        internal static string NgNhanHang {
            get {
                return ResourceManager.GetString("NgNhanHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên dịch vụ không được để trống!.
        /// </summary>
        internal static string NhapDichVu_TenDVEmpty {
            get {
                return ResourceManager.GetString("NhapDichVu_TenDVEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền công không được để trống!
        ///Nếu tiền công phụ thuộc vào chi tiết gia công thì nhập vào 0.
        /// </summary>
        internal static string NhapDichVu_TienCongEmpty {
            get {
                return ResourceManager.GetString("NhapDichVu_TienCongEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ không được để trống!.
        /// </summary>
        internal static string NhapKhachHang_DiaChiEmpty {
            get {
                return ResourceManager.GetString("NhapKhachHang_DiaChiEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không được để trống!.
        /// </summary>
        internal static string NhapKhachHang_SDTEmpty {
            get {
                return ResourceManager.GetString("NhapKhachHang_SDTEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng không được để trống!.
        /// </summary>
        internal static string NhapKhachHang_TenKHEmpty {
            get {
                return ResourceManager.GetString("NhapKhachHang_TenKHEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập hình thức gia công.
        /// </summary>
        internal static string NhapPhieuDichVu_HTGCEmpty {
            get {
                return ResourceManager.GetString("NhapPhieuDichVu_HTGCEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại sản phẩm không được để trống!
        ///Chọn Khác nếu cửa hàng không kinh doanh loại sản phẩm này..
        /// </summary>
        internal static string NhapPhieuDichVu_LoaiSPEmpty {
            get {
                return ResourceManager.GetString("NhapPhieuDichVu_LoaiSPEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đăng kí không được để trống.
        /// </summary>
        internal static string NhapPhieuDichVu_NgayDkEmpty {
            get {
                return ResourceManager.GetString("NhapPhieuDichVu_NgayDkEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giao không được để trống.
        /// </summary>
        internal static string NhapPhieuDichVu_NgayGiaoEmpty {
            get {
                return ResourceManager.GetString("NhapPhieuDichVu_NgayGiaoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giao phải lớn hơn hoặc bằng ngày đăng ký!.
        /// </summary>
        internal static string NhapPhieuDichVu_NgayGiaoTruocNgayDK {
            get {
                return ResourceManager.GetString("NhapPhieuDichVu_NgayGiaoTruocNgayDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng phải lớn hơn 0.
        /// </summary>
        internal static string NhapPhieuDichVu_SoLuongEmpty {
            get {
                return ResourceManager.GetString("NhapPhieuDichVu_SoLuongEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mỗi phiếu dịch vụ phải có ít nhất 1 chi tiết phiếu dịch vụ.
        /// </summary>
        internal static string NhapPhieuDichVu_SoPDVToiThieu {
            get {
                return ResourceManager.GetString("NhapPhieuDichVu_SoPDVToiThieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu dịch vụ được tạo thành công!.
        /// </summary>
        internal static string NhapPhieuDichVu_TaoPDVThanhCong {
            get {
                return ResourceManager.GetString("NhapPhieuDichVu_TaoPDVThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nhận hàng không được để trống.
        /// </summary>
        internal static string NhapPhieuGiaCong_NgayNhanHangEmpty {
            get {
                return ResourceManager.GetString("NhapPhieuGiaCong_NgayNhanHangEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày thanh toán không được để trống.
        /// </summary>
        internal static string NhapPhieuGiaCong_NgayThanhToanEmpty {
            get {
                return ResourceManager.GetString("NhapPhieuGiaCong_NgayThanhToanEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày thanh toán phải lớn hơn hoặc bằng ngày nhận hàng!.
        /// </summary>
        internal static string NhapPhieuGiaCong_NgayThanhToanTruocNgayNhanHang {
            get {
                return ResourceManager.GetString("NhapPhieuGiaCong_NgayThanhToanTruocNgayNhanHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mỗi phiếu gia công phải có ít nhất 1 chi tiết phiếu gia công.
        /// </summary>
        internal static string NhapPhieuGiaCong_SLChiTietPGCToiThieu {
            get {
                return ResourceManager.GetString("NhapPhieuGiaCong_SLChiTietPGCToiThieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng gia công không được lớn hơn số lượng sản phẩm!.
        /// </summary>
        internal static string NhapPhieuGiaCong_SLGiaCongLonHonSLCo {
            get {
                return ResourceManager.GetString("NhapPhieuGiaCong_SLGiaCongLonHonSLCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập vào số lượng lớn hơn 0!.
        /// </summary>
        internal static string NhapPhieuGiaCong_SoLuongBeHonKhong {
            get {
                return ResourceManager.GetString("NhapPhieuGiaCong_SoLuongBeHonKhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải chọn sản phẩm cần gia công!.
        /// </summary>
        internal static string NhapPhieuGiaCong_SPCanGiaCongEmpty {
            get {
                return ResourceManager.GetString("NhapPhieuGiaCong_SPCanGiaCongEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu gia công được tạo thành công!.
        /// </summary>
        internal static string NhapPhieuGiaCong_TaoPGCThanhCong {
            get {
                return ResourceManager.GetString("NhapPhieuGiaCong_TaoPGCThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thợ không được để trống.
        /// </summary>
        internal static string NhapPhieuGiaCong_TenThoEmpty {
            get {
                return ResourceManager.GetString("NhapPhieuGiaCong_TenThoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập vào tiền công!.
        /// </summary>
        internal static string NhapPhieuGiaCong_TienCongEmpty {
            get {
                return ResourceManager.GetString("NhapPhieuGiaCong_TienCongEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        internal static string SDT {
            get {
                return ResourceManager.GetString("SDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string SoLuong {
            get {
                return ResourceManager.GetString("SoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền nợ.
        /// </summary>
        internal static string SoTienNo {
            get {
                return ResourceManager.GetString("SoTienNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa chi tiết phiếu dịch vụ thành công!.
        /// </summary>
        internal static string SuaCTPDVThanhCong {
            get {
                return ResourceManager.GetString("SuaCTPDVThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa phiếu dịch vụ thành công!.
        /// </summary>
        internal static string SuaPhieuDichVu_SuaPDVThanhCong {
            get {
                return ResourceManager.GetString("SuaPhieuDichVu_SuaPDVThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm chi tiết phiếu dịch vụ thành công!.
        /// </summary>
        internal static string SuaPhieuDichVu_ThemCTPDVThanhCong {
            get {
                return ResourceManager.GetString("SuaPhieuDichVu_ThemCTPDVThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xoá chi tiết phiếu dịch vụ đã được gia công!.
        /// </summary>
        internal static string SuaPhieuDichVu_XoaCTPDVDaGiaCongError {
            get {
                return ResourceManager.GetString("SuaPhieuDichVu_XoaCTPDVDaGiaCongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá chi tiết phiếu dịch vụ thành công!.
        /// </summary>
        internal static string SuaPhieuDichVu_XoaCTPDVThanhCong {
            get {
                return ResourceManager.GetString("SuaPhieuDichVu_XoaCTPDVThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Số lượng tối đa có thể nhập: .
        /// </summary>
        internal static string SuaPhieuGiaCong_SLToiDaCoTheNhap {
            get {
                return ResourceManager.GetString("SuaPhieuGiaCong_SLToiDaCoTheNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng nhập vào lớn hơn số lượng sản phẩm nhận từ khách hàng.
        /// </summary>
        internal static string SuaPhieuGiaCong_SoLuongNhapGCToiDa {
            get {
                return ResourceManager.GetString("SuaPhieuGiaCong_SoLuongNhapGCToiDa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa chi tiết phiếu gia công thành công!.
        /// </summary>
        internal static string SuaPhieuGiaCong_SuaCTPGCThanhCong {
            get {
                return ResourceManager.GetString("SuaPhieuGiaCong_SuaCTPGCThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa phiếu gia công thành công!.
        /// </summary>
        internal static string SuaPhieuGiaCong_SuaPGCThanhCong {
            get {
                return ResourceManager.GetString("SuaPhieuGiaCong_SuaPGCThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm chi tiết phiếu gia công thành công!.
        /// </summary>
        internal static string SuaPhieuGiaCong_ThemCTPGCThanhCong {
            get {
                return ResourceManager.GetString("SuaPhieuGiaCong_ThemCTPGCThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá chi tiết phiếu gia công thành công!.
        /// </summary>
        internal static string SuaPhieuGiaCong_XoaCTPGCThanhCong {
            get {
                return ResourceManager.GetString("SuaPhieuGiaCong_XoaCTPGCThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên dịch vụ.
        /// </summary>
        internal static string TenDichVu {
            get {
                return ResourceManager.GetString("TenDichVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng.
        /// </summary>
        internal static string TenKH {
            get {
                return ResourceManager.GetString("TenKH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên loại sản phẩm.
        /// </summary>
        internal static string TenLoaiSP {
            get {
                return ResourceManager.GetString("TenLoaiSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên.
        /// </summary>
        internal static string TenNV {
            get {
                return ResourceManager.GetString("TenNV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thợ.
        /// </summary>
        internal static string TenTho {
            get {
                return ResourceManager.GetString("TenTho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền.
        /// </summary>
        internal static string ThanhTien {
            get {
                return ResourceManager.GetString("ThanhTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thành công!.
        /// </summary>
        internal static string ThemThanhCong {
            get {
                return ResourceManager.GetString("ThemThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        internal static string ThoatKhoiForm {
            get {
                return ResourceManager.GetString("ThoatKhoiForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền công.
        /// </summary>
        internal static string TienCong {
            get {
                return ResourceManager.GetString("TienCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        internal static string TitleMessageBox_Error {
            get {
                return ResourceManager.GetString("TitleMessageBox_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string TitleMessageBox_ThongBao {
            get {
                return ResourceManager.GetString("TitleMessageBox_ThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền.
        /// </summary>
        internal static string TongTien {
            get {
                return ResourceManager.GetString("TongTien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công!.
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
    }
}
